import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Nav from '../components/Nav';
import Web3ContextProvider from '../hooks/useWeb3Context';
import { ToastContainer } from 'react-toastify';
const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <Web3ContextProvider>
            <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} relative overflow-x-hidden antialiased `}>
                    <Nav />
                    <ToastContainer />
                    {children}
                </body>
            </html>
        </Web3ContextProvider>
    );
}
